### ISSUE TITLE
테스트결과

### ISSUE THREAD

**Issue by le0park** [ljwon1995/GoodbyeCampus#10]
스크린샷 내용 이해 x

![Screenshot_20200523-225347_KakaoTalk](https://user-images.githubusercontent.com/29172189/82732546-dda4e980-9d48-11ea-8105-9b01780e4178.jpg)
![Screenshot_20200523-225340_KakaoTalk](https://user-images.githubusercontent.com/29172189/82732552-e39aca80-9d48-11ea-9c3e-70bc1ccf381b.jpg)
![Screenshot_20200523-225331_KakaoTalk](https://user-images.githubusercontent.com/29172189/82732553-e695bb00-9d48-11ea-8eeb-b40fd1f831a2.jpg)
![Screenshot_20200523-225319_KakaoTalk](https://user-images.githubusercontent.com/29172189/82732556-ea294200-9d48-11ea-8a8f-84893ac25ce8.jpg)
![Screenshot_20200523-225313_KakaoTalk](https://user-images.githubusercontent.com/29172189/82732560-edbcc900-9d48-11ea-9132-abb574bdfb0c.jpg)

**Comment by ljwon1995** [comment]
Solved
