### ISSUE TITLE
Service doesn't work with these keywords.

### ISSUE THREAD

**Issue by SeongYunKim** [ljwon1995/GoodbyeCampus#7]
Service doesn't work with these keywords.

나 교수님이랑 상담 해야 해?
나 몇학점 남았어?
나 졸업 할수있어?
전필이 몇학점 남았지?
나 한자 통과했나?
나 공학인증 가능?
나 필수 교양 다 들었나?

**Comment by ljwon1995** [comment]
We dealt with that. Thanks :)
