### ISSUE TITLE
테스트 결과

### ISSUE THREAD

**Issue by compass0** [ljwon1995/GoodbyeCampus#8]
테스트 결과는?

인터넷 단골 용어 "ㅎㅇ" 입력시 알지 못합니다
"?" 물음표 입력시에 아무런 말도 하지 않습니다 
"나 졸업하려면 몇학점 더 들어야돼?"에 알지 못합니다. (답변 : "다른 질문은 없나요?")
"졸업학점" 입력시 알지 못합니다.
"졸업학점 알려줘" 입력시 알지 못합니다.

 “나 졸업 가능해?”
 “나 졸업하려면 몇 학점 더 들어야해?”
 “나 필수과목 다 들었어?”
 “나 졸업논문 내야돼?”
이 정해진 4개에서 여기서 물음표가 빠지거나 느낌표가 들어가거나 하면 알아듣지 못합니다

**Comment by ljwon1995** [comment]
We dealt with that. Thanks :)
